// 710 = 7 * 100 + 1 * 10 + 0 * 1 = 7 * 10^2 + 1 * 10 ^ 1 + 0 * 10^0
// 710 / 10, q = 71, r = 0
// 71 / 10, q = 7, r = 1
// 7 / 10, q = 0, r = 7



/**  
 * Psuedo Code:
 * 1. Copy input number to a temporary variable num.
 * 2. Initialize a counter variable to 0.
 * 2. Start a while loop which will run until num / 10 == 0.
 * 3. In each run, divide num by 10 and increment the counter by 1.
 * 4. Re-initialize num to input number.
 * 5. Create temp variable output. Initialize it to 0.
 * 6. Run another loop with variable i from counter - 1 to 0 and decrement i by 1 in each run.
 * 7. In each run, do num % 10. Multiply the remainder by 10 to the power of i.
 * 8. Add the result to output variable.
 * 9. Make num = num / 10 and then continue the loop until num / 10 == 0.
 * 10. Print the output variable.
 */
/**
 * Pattern:
 * Running log(n) times.
 */


// Code has been generated by AI based on the pseudo code I wrote above.

import readline from "readline";

const r1 = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

r1.question("Enter a number to reverse\n", (num) => {
        reverseNumber(Number(num));
        r1.close();
    }
);

// Time Complexity: not O(n) as I thought. O(log(n)) since each time we run the loop we are dividing by 10.
const reverseNumber = (num: number) => {
    let temp = num;
    let counter = 0;
    // while(temp / 10 >= 1) { // AI gave this condition but it is wrong. For 7, temp / 10 = 0.7 which is < 1, so loop will not run and counter will be 0. But we want counter to be 1 for single digit numbers.
    while(temp !== 0) { // I corrected this but temp / 10 results in float value, so we can have precision issues. So I will use temp / 10 >= 1 condition but I will make temp an integer by using Math.floor(temp / 10).
        // temp = temp / 10; // Bug in my code since this results in floating point value.
        temp = Math.floor(temp / 10);
        counter++;
        // console.log(`Counter is ${counter}, temp is ${temp}`);
    }
    temp = num;
    let output = 0;
    // for(let i = counter; i >= 0; i--) { // AI wrote this wrong despite my pseudo code which told to run from counter - 1 to 0. If we run from counter to 0, we will have an extra 0 at the end of the output. E.g. for input 7, counter will be 1, so loop will run for i = 1 and i = 0. For i = 1, output will be 7 * 10^1 = 70 and for i = 0, output will be 0 * 10^0 = 0. So final output will be 70 + 0 = 70 instead of 7.
    for(let i = counter - 1; i >= 0; i--) { // Now when num = 7, counter will be 1, so loop will run only for i = 0. For i = 0, output will be 7 * 10^0 = 7. So final output will be 7 which is correct.
        output = output + (temp % 10) * Math.pow(10, i);
        temp = Math.floor(temp / 10);
    }
    console.log(output);
}
